@baseUrl = http://localhost:5102/api/Employee

### Test (Esistente)
DELETE {{baseUrl}}/MARIOROSSI

### Test (Inesistente)
DELETE {{baseUrl}}/NON-ESISTO

### Test (dati non conformi)
DELETE {{baseUrl}}/ERRORE