@baseUrl = http://localhost:5102/api/Employee

### Test (esistente)
DELETE {{baseUrl}}/MARIOROSSI

### Test (inesistente)
DELETE {{baseUrl}}/NON-ESISTO

### Test (dati non conformi / errore validazione)
DELETE {{baseUrl}}/ERRORE