@baseUrl = http://localhost:5102/api/Employee

### Test (Esistente)
GET {{baseUrl}}/MARIOROSSI

### Test (Inesistente)
GET {{baseUrl}}/NON-ESISTO

### Test (dati non conformi)
GET {{baseUrl}}/ERRORE

### Test => Lista
GET {{baseUrl}}