@baseUrl = http://localhost:5102/api/Person

### Test (esistente)
DELETE {{baseUrl}}/RSSMRA80A01H501U

### Test (inesistente)
DELETE {{baseUrl}}/NON-ESISTO......

### Test (dati non conformi / errore validazione)
DELETE {{baseUrl}}/ERRORE