@baseUrl = http://localhost:5102/api/Person

### Test => Update Persona (Successo)
PUT {{baseUrl}}
Content-Type: application/json

{
  "codiceFiscale": "RSSMRA80A01H501U",
  "nome": "Mario",
  "cognome": "Rossi",
  "sesso": "M",
  "dataNascita": "1980-01-01",
  "citta": "Roma",
  "provincia": "RM",
  "codicePostale": "00100",
  "indirizzo": "Via Roma 1",
  "numeroContatto": "+393331234567",
  "email": "mario.rossi@example.com"
}

### Test => Utente inesistente
PUT {{baseUrl}}
Content-Type: application/json

{
  "codiceFiscale": "UTENTEINESISTE..",
  "nome": "Mario",
  "cognome": "Rossi",
  "sesso": "M",
  "dataNascita": "1980-01-01",
  "citta": "Roma",
  "provincia": "RM",
  "codicePostale": "00100",
  "indirizzo": "Via Roma 1",
  "numeroContatto": "333",
  "email": "mario.rossi@example.com"
}

### Test => Errore di Validazione (Esempio CF corto e Sesso errato)
PUT {{baseUrl}}
Content-Type: application/json

{
    "codiceFiscale": "CORTO",
    "nome": "Mario",
    "cognome": "Rossi",
    "sesso": "X",
    "dataNascita": "1980-01-01",
    "citta": "Roma",
    "provincia": "RM",
    "codicePostale": "00100",
    "indirizzo": "Via Roma 1",
    "numeroContatto": "333",
    "email": "email-non-valida"
}


1. Lo Spazio Vuoto: È fondamentale che ci sia una riga vuota tra gli header (come Content-Type) 
e il corpo del JSON. Se non la metti, il server non leggerà il corpo della richiesta.

2. Naming Convention: Anche se in C# le proprietà iniziano con la maiuscola (Nome), 
per impostazione predefinita l'API si aspetta il formato camelCase (nome).

3. Formato Data: La DateOnly (o DateTime) va scritta tra virgolette nel formato standard ISO: "YYYY-MM-DD".