@baseUrl = http://localhost:5102/api/Product

### Test (esistente)
DELETE {{baseUrl}}/SKU-99999

### Test (inesistente)
DELETE {{baseUrl}}/SKU-INESISTENTE

### Test (dati non conformi / errore validazione)
DELETE {{baseUrl}}/ECCESSO_DI_CARATTERI_OLTRE_IL_LIMITE