// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using store.api._.Data;

#nullable disable

namespace store.api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260321171908_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("store.core._.Domain.Entity.Catalog.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasColumnOrder(6);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at")
                        .HasColumnOrder(7);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome")
                        .HasColumnOrder(3);

                    b.Property<int>("Qnt")
                        .HasColumnType("int")
                        .HasColumnName("qnt")
                        .HasColumnOrder(4);

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("varchar(30")
                        .HasColumnName("sku")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("prodotti", (string)null);
                });

            modelBuilder.Entity("store.core._.Domain.Entity.User.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodiceCliente")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("codice_cliente")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted")
                        .HasColumnOrder(6);

                    b.Property<bool>("IsFidelizzato")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_fidelizzato")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsIscrittoNewsletter")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_iscritto_newsletter")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at")
                        .HasColumnOrder(8);

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("person_id")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("CodiceCliente")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("clienti", (string)null);
                });

            modelBuilder.Entity("store.core._.Domain.Entity.User.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodiceMeccanografico")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("codice_meccanografico")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasColumnOrder(8);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at")
                        .HasColumnOrder(9);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(24)")
                        .HasColumnName("password")
                        .HasColumnOrder(4);

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("person_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ruolo")
                        .HasColumnOrder(5);

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salario")
                        .HasColumnOrder(6);

                    b.HasKey("Id");

                    b.HasIndex("CodiceMeccanografico")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("dipendenti", (string)null);
                });

            modelBuilder.Entity("store.core._.Domain.Entity.User.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("citta")
                        .HasColumnOrder(7);

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("codice_fiscale")
                        .HasColumnOrder(2);

                    b.Property<string>("CodicePostale")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("codice_postale")
                        .HasColumnOrder(9);

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cognome")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasColumnOrder(14);

                    b.Property<DateOnly>("DataNascita")
                        .HasColumnType("date")
                        .HasColumnName("data_nascita")
                        .HasColumnOrder(6);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email")
                        .HasColumnOrder(12);

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("indirizzo")
                        .HasColumnOrder(10);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted")
                        .HasColumnOrder(13);

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at")
                        .HasColumnOrder(15);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome")
                        .HasColumnOrder(3);

                    b.Property<string>("NumeroContatto")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numero_contatto")
                        .HasColumnOrder(11);

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("provincia")
                        .HasColumnOrder(8);

                    b.Property<string>("Sesso")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("sesso")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("CodiceFiscale")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("persone", (string)null);
                });

            modelBuilder.Entity("store.core._.Domain.Entity.User.Client", b =>
                {
                    b.HasOne("store.core._.Domain.Entity.User.Person", "Person")
                        .WithOne()
                        .HasForeignKey("store.core._.Domain.Entity.User.Client", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("store.core._.Domain.Entity.User.Employee", b =>
                {
                    b.HasOne("store.core._.Domain.Entity.User.Person", "Person")
                        .WithOne()
                        .HasForeignKey("store.core._.Domain.Entity.User.Employee", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
